import {
  homeOutline,
  pricetagsOutline,
  peopleOutline,
  receiptOutline,
  personCircleOutline,
  shieldCheckmarkOutline,
} from 'ionicons/icons';

export const navegacion = [
  {
    id: 'inicio',
    grupo_menu: 'operacion',
    titulo: 'Inicio',
    orden: 10,
    ruta: '/app/inicio',
    icono: homeOutline,
    componente: () => import('@/views/inicio_page.vue'),
    roles: ['*'],
    menu_roles: ['*'],
    tab_roles: ['*'],
  },
  {
    id: 'productos',
    grupo_menu: 'operacion',
    titulo: 'Productos',
    orden: 20,
    ruta: '/app/productos',
    icono: pricetagsOutline,
    componente: () => import('@/views/productos_page.vue'),
    roles: ['ADMIN', 'VETERINARIO'],
    menu_roles: ['ADMIN', 'VETERINARIO'],
    tab_roles: ['ADMIN', 'VETERINARIO'],
  },
  {
    id: 'clientes',
    grupo_menu: 'operacion',
    titulo: 'Clientes',
    orden: 30,
    ruta: '/app/clientes',
    icono: peopleOutline,
    componente: () => import('@/views/clientes_page.vue'),
    roles: ['ADMIN', 'VETERINARIO'],
    menu_roles: ['ADMIN', 'VETERINARIO'],
    tab_roles: ['ADMIN', 'VETERINARIO'],
  },
  {
    id: 'pedidos',
    grupo_menu: 'operacion',
    titulo: 'Pedidos',
    orden: 40,
    ruta: '/app/pedidos',
    icono: receiptOutline,
    componente: () => import('@/views/pedidos_page.vue'),
    roles: ['ADMIN', 'VETERINARIO'],
    menu_roles: ['ADMIN', 'VETERINARIO'],
    tab_roles: ['ADMIN', 'VETERINARIO'],
  },
  {
    id: 'usuarios',
    grupo_menu: 'configuracion',
    titulo: 'Usuarios',
    orden: 45,
    ruta: '/app/usuarios',
    icono: shieldCheckmarkOutline,
    componente: () => import('@/views/usuarios_page.vue'),
    roles: ['ADMIN'],
    menu_roles: ['ADMIN'],
    tab_roles: [],
  },
  {
    id: 'cuenta',
    grupo_menu: 'configuracion',
    titulo: 'Mi cuenta',
    orden: 50,
    ruta: '/app/cuenta',
    icono: personCircleOutline,
    componente: () => import('@/views/cuenta_page.vue'),
    roles: ['*'],
    menu_roles: ['*'],
    tab_roles: ['*'],
  },
];